/* ==================== RIVALS CARDS ====================
 * Flat catalogue of universal Rivals cards (objectives, ploys, upgrades),
 * parsed from the printed card lists. Each card:
 *   { code, set, number, category, name }
 *   - code:     unique short id, e.g. 'CC17' (set prefix + number)
 *   - set:      two-letter deck/set prefix (see CARD_SETS below)
 *   - number:   the printed number within that set
 *   - category: 'Objective' | 'Ploy' | 'Upgrade'
 *   - name:     printed card name
 *
 * 384 cards total: 144 objectives, 120 ploys, 120 upgrades, across 12 sets.
 *
 * Helpers:
 *   CARD_BY_CODE   — { code: card } lookup
 *   cardName(code) — returns the card's name, or the code itself if unknown
 *   cardsBySet(prefix) / cardsByCategory(cat) — filtered arrays
 */

export const CARD_SETS = {
  BL: 'Blade',      ES: 'Emberstone',  PL: 'Prospector',
  CC: 'Cataclysm',  RF: 'Rampager',    WR: 'Wrecker',
  EK: 'Ekayrie',    RS: 'Raider',      RG: 'Rager',
  HG: 'Homeland',   DY: 'Duo',         NP: 'Nexus',
};
// NB: CARD_SETS values are convenience labels for the two-letter prefixes and
// may not match official Rivals deck titles exactly — the `set` prefix on each
// card is the authoritative key. Adjust the labels here if needed.

export const CARDS = [
  // ---- Objectives ----
  { code: 'BL1', set: 'BL', number: 1, category: 'Objective', name: 'Strike the Head' },
  { code: 'BL2', set: 'BL', number: 2, category: 'Objective', name: 'Branching Fate' },
  { code: 'BL3', set: 'BL', number: 3, category: 'Objective', name: 'Perfect Strike' },
  { code: 'BL4', set: 'BL', number: 4, category: 'Objective', name: 'Critical Effort' },
  { code: 'BL5', set: 'BL', number: 5, category: 'Objective', name: 'Get Stuck In' },
  { code: 'BL6', set: 'BL', number: 6, category: 'Objective', name: 'Strong Start' },
  { code: 'BL7', set: 'BL', number: 7, category: 'Objective', name: 'Keep Choppin\'' },
  { code: 'BL8', set: 'BL', number: 8, category: 'Objective', name: 'Fields of Blood' },
  { code: 'BL9', set: 'BL', number: 9, category: 'Objective', name: 'Go All Out' },
  { code: 'BL10', set: 'BL', number: 10, category: 'Objective', name: 'On the Edge' },
  { code: 'BL11', set: 'BL', number: 11, category: 'Objective', name: 'Denial' },
  { code: 'BL12', set: 'BL', number: 12, category: 'Objective', name: 'Annihilation' },
  { code: 'ES1', set: 'ES', number: 1, category: 'Objective', name: 'Sally Forth' },
  { code: 'ES2', set: 'ES', number: 2, category: 'Objective', name: 'Stand Firm' },
  { code: 'ES3', set: 'ES', number: 3, category: 'Objective', name: 'Step by Step' },
  { code: 'ES4', set: 'ES', number: 4, category: 'Objective', name: 'Unassailable' },
  { code: 'ES5', set: 'ES', number: 5, category: 'Objective', name: 'Aggressive Defender' },
  { code: 'ES6', set: 'ES', number: 6, category: 'Objective', name: 'Careful Advance' },
  { code: 'ES7', set: 'ES', number: 7, category: 'Objective', name: 'Hold Treasure Token 1 or 2' },
  { code: 'ES8', set: 'ES', number: 8, category: 'Objective', name: 'Hold Treasure Token 3 or 4' },
  { code: 'ES9', set: 'ES', number: 9, category: 'Objective', name: 'Hold Treasure Token 5' },
  { code: 'ES10', set: 'ES', number: 10, category: 'Objective', name: 'Slow Advance' },
  { code: 'ES11', set: 'ES', number: 11, category: 'Objective', name: 'Iron Grasp' },
  { code: 'ES12', set: 'ES', number: 12, category: 'Objective', name: 'Supremacy' },
  { code: 'PL1', set: 'PL', number: 1, category: 'Objective', name: 'Broken Prospects' },
  { code: 'PL2', set: 'PL', number: 2, category: 'Objective', name: 'Against the Odds' },
  { code: 'PL3', set: 'PL', number: 3, category: 'Objective', name: 'Lost in the Depths' },
  { code: 'PL4', set: 'PL', number: 4, category: 'Objective', name: 'Desolate Homeland' },
  { code: 'PL5', set: 'PL', number: 5, category: 'Objective', name: 'Torn Landscape' },
  { code: 'PL6', set: 'PL', number: 6, category: 'Objective', name: 'Strip the Realm' },
  { code: 'PL7', set: 'PL', number: 7, category: 'Objective', name: 'Aggressive Claimant' },
  { code: 'PL8', set: 'PL', number: 8, category: 'Objective', name: 'Claim the Prize' },
  { code: 'PL9', set: 'PL', number: 9, category: 'Objective', name: 'Delving for Wealth' },
  { code: 'PL10', set: 'PL', number: 10, category: 'Objective', name: 'Share the Load' },
  { code: 'PL11', set: 'PL', number: 11, category: 'Objective', name: 'Hostile Takeover' },
  { code: 'PL12', set: 'PL', number: 12, category: 'Objective', name: 'Careful Survey' },
  { code: 'CC1', set: 'CC', number: 1, category: 'Objective', name: 'Spread Havoc' },
  { code: 'CC2', set: 'CC', number: 2, category: 'Objective', name: 'Hounds of War' },
  { code: 'CC3', set: 'CC', number: 3, category: 'Objective', name: 'Set Explosives' },
  { code: 'CC4', set: 'CC', number: 4, category: 'Objective', name: 'Wreckers' },
  { code: 'CC5', set: 'CC', number: 5, category: 'Objective', name: 'Uneven Contest' },
  { code: 'CC6', set: 'CC', number: 6, category: 'Objective', name: 'Loaded for Bear' },
  { code: 'CC7', set: 'CC', number: 7, category: 'Objective', name: 'Collateral Damage' },
  { code: 'CC8', set: 'CC', number: 8, category: 'Objective', name: 'Too Close for Comfort' },
  { code: 'CC9', set: 'CC', number: 9, category: 'Objective', name: 'Shocking Assault' },
  { code: 'CC10', set: 'CC', number: 10, category: 'Objective', name: 'Nowhere to Run' },
  { code: 'CC11', set: 'CC', number: 11, category: 'Objective', name: 'The Perfect Cut' },
  { code: 'CC12', set: 'CC', number: 12, category: 'Objective', name: 'Overwhelming Force' },
  { code: 'RF1', set: 'RF', number: 1, category: 'Objective', name: 'Aim for the Top' },
  { code: 'RF2', set: 'RF', number: 2, category: 'Objective', name: 'Arena Mortis' },
  { code: 'RF3', set: 'RF', number: 3, category: 'Objective', name: 'Best Foot Forward' },
  { code: 'RF4', set: 'RF', number: 4, category: 'Objective', name: 'Bloodbathed Rampager' },
  { code: 'RF5', set: 'RF', number: 5, category: 'Objective', name: 'Bloody Momentum' },
  { code: 'RF6', set: 'RF', number: 6, category: 'Objective', name: 'Frenzied Rush' },
  { code: 'RF7', set: 'RF', number: 7, category: 'Objective', name: 'Living Bludgeon' },
  { code: 'RF8', set: 'RF', number: 8, category: 'Objective', name: 'Red Aftermath' },
  { code: 'RF9', set: 'RF', number: 9, category: 'Objective', name: 'Sally Forth' },
  { code: 'RF10', set: 'RF', number: 10, category: 'Objective', name: 'Savage Sprinter' },
  { code: 'RF11', set: 'RF', number: 11, category: 'Objective', name: 'Unrelenting Massacre' },
  { code: 'RF12', set: 'RF', number: 12, category: 'Objective', name: 'Vicious Brawl' },
  { code: 'WR1', set: 'WR', number: 1, category: 'Objective', name: 'Alone in the Dark' },
  { code: 'WR2', set: 'WR', number: 2, category: 'Objective', name: 'Bloody and Bruised' },
  { code: 'WR3', set: 'WR', number: 3, category: 'Objective', name: 'Careful Advance' },
  { code: 'WR4', set: 'WR', number: 4, category: 'Objective', name: 'Living on the Edge' },
  { code: 'WR5', set: 'WR', number: 5, category: 'Objective', name: 'Low on Options' },
  { code: 'WR6', set: 'WR', number: 6, category: 'Objective', name: 'Out of the Frying Pan' },
  { code: 'WR7', set: 'WR', number: 7, category: 'Objective', name: 'Ploymaster' },
  { code: 'WR8', set: 'WR', number: 8, category: 'Objective', name: 'Predictable End' },
  { code: 'WR9', set: 'WR', number: 9, category: 'Objective', name: 'Spread Out!' },
  { code: 'WR10', set: 'WR', number: 10, category: 'Objective', name: 'Stay Close' },
  { code: 'WR11', set: 'WR', number: 11, category: 'Objective', name: 'Strong Start' },
  { code: 'WR12', set: 'WR', number: 12, category: 'Objective', name: 'Unsafe Ground' },
  { code: 'EK1', set: 'EK', number: 1, category: 'Objective', name: 'Aggressive Defender' },
  { code: 'EK2', set: 'EK', number: 2, category: 'Objective', name: 'All In' },
  { code: 'EK3', set: 'EK', number: 3, category: 'Objective', name: 'Behind Enemy Lines' },
  { code: 'EK4', set: 'EK', number: 4, category: 'Objective', name: 'Calm Before the Storm' },
  { code: 'EK5', set: 'EK', number: 5, category: 'Objective', name: 'Double Team' },
  { code: 'EK6', set: 'EK', number: 6, category: 'Objective', name: 'Immovable' },
  { code: 'EK7', set: 'EK', number: 7, category: 'Objective', name: 'Power in Numbers' },
  { code: 'EK8', set: 'EK', number: 8, category: 'Objective', name: 'Risky Position' },
  { code: 'EK9', set: 'EK', number: 9, category: 'Objective', name: 'Sneak Into Position' },
  { code: 'EK10', set: 'EK', number: 10, category: 'Objective', name: 'Trial of the Tempered' },
  { code: 'EK11', set: 'EK', number: 11, category: 'Objective', name: 'Two-pronged Assault' },
  { code: 'EK12', set: 'EK', number: 12, category: 'Objective', name: 'Usurper' },
  { code: 'RS1', set: 'RS', number: 1, category: 'Objective', name: 'A Sure Bet' },
  { code: 'RS2', set: 'RS', number: 2, category: 'Objective', name: 'Certain Aggression' },
  { code: 'RS3', set: 'RS', number: 3, category: 'Objective', name: 'Critical Risk' },
  { code: 'RS4', set: 'RS', number: 4, category: 'Objective', name: 'Emberstone Stash' },
  { code: 'RS5', set: 'RS', number: 5, category: 'Objective', name: 'Hoarder\'s Hovel' },
  { code: 'RS6', set: 'RS', number: 6, category: 'Objective', name: 'Invade' },
  { code: 'RS7', set: 'RS', number: 7, category: 'Objective', name: 'Looted Realmstone' },
  { code: 'RS8', set: 'RS', number: 8, category: 'Objective', name: 'Pillage' },
  { code: 'RS9', set: 'RS', number: 9, category: 'Objective', name: 'Ragerock Strike' },
  { code: 'RS10', set: 'RS', number: 10, category: 'Objective', name: 'Realmstone Raid' },
  { code: 'RS11', set: 'RS', number: 11, category: 'Objective', name: 'Reckless Gambit' },
  { code: 'RS12', set: 'RS', number: 12, category: 'Objective', name: 'Roused Violence' },
  { code: 'RG1', set: 'RG', number: 1, category: 'Objective', name: 'Aggressive Expansion' },
  { code: 'RG2', set: 'RG', number: 2, category: 'Objective', name: 'Best Foot Forward' },
  { code: 'RG3', set: 'RG', number: 3, category: 'Objective', name: 'Blinded by Rage' },
  { code: 'RG4', set: 'RG', number: 4, category: 'Objective', name: 'Coordinated Assault' },
  { code: 'RG5', set: 'RG', number: 5, category: 'Objective', name: 'Into the Fire' },
  { code: 'RG6', set: 'RG', number: 6, category: 'Objective', name: 'No Contest' },
  { code: 'RG7', set: 'RG', number: 7, category: 'Objective', name: 'No Escape' },
  { code: 'RG8', set: 'RG', number: 8, category: 'Objective', name: 'No Respite' },
  { code: 'RG9', set: 'RG', number: 9, category: 'Objective', name: 'Overwhelming Presence' },
  { code: 'RG10', set: 'RG', number: 10, category: 'Objective', name: 'Sever the Head' },
  { code: 'RG11', set: 'RG', number: 11, category: 'Objective', name: 'Supreme Slayer' },
  { code: 'RG12', set: 'RG', number: 12, category: 'Objective', name: 'Unrelenting Massacre' },
  { code: 'HG1', set: 'HG', number: 1, category: 'Objective', name: 'Back Off!' },
  { code: 'HG2', set: 'HG', number: 2, category: 'Objective', name: 'Bloodscent' },
  { code: 'HG3', set: 'HG', number: 3, category: 'Objective', name: 'Hands Off!' },
  { code: 'HG4', set: 'HG', number: 4, category: 'Objective', name: 'Home Advantage' },
  { code: 'HG5', set: 'HG', number: 5, category: 'Objective', name: 'Lead by Example' },
  { code: 'HG6', set: 'HG', number: 6, category: 'Objective', name: 'No Business Here' },
  { code: 'HG7', set: 'HG', number: 7, category: 'Objective', name: 'No Trespassers' },
  { code: 'HG8', set: 'HG', number: 8, category: 'Objective', name: 'Pinned!' },
  { code: 'HG9', set: 'HG', number: 9, category: 'Objective', name: 'Ready or Not' },
  { code: 'HG10', set: 'HG', number: 10, category: 'Objective', name: 'Spoiling for a Fight' },
  { code: 'HG11', set: 'HG', number: 11, category: 'Objective', name: 'This is Our Turf!' },
  { code: 'HG12', set: 'HG', number: 12, category: 'Objective', name: 'Usurped' },
  { code: 'DY1', set: 'DY', number: 1, category: 'Objective', name: 'Aggressive Unity' },
  { code: 'DY2', set: 'DY', number: 2, category: 'Objective', name: 'Beatdown' },
  { code: 'DY3', set: 'DY', number: 3, category: 'Objective', name: 'Closed Down' },
  { code: 'DY4', set: 'DY', number: 4, category: 'Objective', name: 'Got Your Back!' },
  { code: 'DY5', set: 'DY', number: 5, category: 'Objective', name: 'Helping Hand' },
  { code: 'DY6', set: 'DY', number: 6, category: 'Objective', name: 'Hemmed In' },
  { code: 'DY7', set: 'DY', number: 7, category: 'Objective', name: 'Inevitable Outcome' },
  { code: 'DY8', set: 'DY', number: 8, category: 'Objective', name: 'Infiltrate' },
  { code: 'DY9', set: 'DY', number: 9, category: 'Objective', name: 'Outmuscle' },
  { code: 'DY10', set: 'DY', number: 10, category: 'Objective', name: 'Tag Team' },
  { code: 'DY11', set: 'DY', number: 11, category: 'Objective', name: 'Tandem Assault' },
  { code: 'DY12', set: 'DY', number: 12, category: 'Objective', name: 'United Aid' },
  { code: 'NP1', set: 'NP', number: 1, category: 'Objective', name: 'Seized' },
  { code: 'NP2', set: 'NP', number: 2, category: 'Objective', name: 'Break Out' },
  { code: 'NP3', set: 'NP', number: 3, category: 'Objective', name: 'Claimed' },
  { code: 'NP4', set: 'NP', number: 4, category: 'Objective', name: 'Pound for Pound' },
  { code: 'NP5', set: 'NP', number: 5, category: 'Objective', name: 'All Part of the Plan' },
  { code: 'NP6', set: 'NP', number: 6, category: 'Objective', name: 'Calculated Strike' },
  { code: 'NP7', set: 'NP', number: 7, category: 'Objective', name: 'Audacity' },
  { code: 'NP8', set: 'NP', number: 8, category: 'Objective', name: 'Close the Vice' },
  { code: 'NP9', set: 'NP', number: 9, category: 'Objective', name: 'Slow Advance' },
  { code: 'NP10', set: 'NP', number: 10, category: 'Objective', name: 'Domination' },
  { code: 'NP11', set: 'NP', number: 11, category: 'Objective', name: 'Lone Wolves' },
  { code: 'NP12', set: 'NP', number: 12, category: 'Objective', name: 'Skin of Their Teeth' },
  // ---- Ploys ----
  { code: 'BL13', set: 'BL', number: 13, category: 'Ploy', name: 'Determined Effort' },
  { code: 'BL14', set: 'BL', number: 14, category: 'Ploy', name: 'Twist the Knife' },
  { code: 'BL15', set: 'BL', number: 15, category: 'Ploy', name: 'Lure of Battle' },
  { code: 'BL16', set: 'BL', number: 16, category: 'Ploy', name: 'Sidestep' },
  { code: 'BL17', set: 'BL', number: 17, category: 'Ploy', name: 'Commanding Stride' },
  { code: 'BL18', set: 'BL', number: 18, category: 'Ploy', name: 'Illusory Fighter' },
  { code: 'BL19', set: 'BL', number: 19, category: 'Ploy', name: 'Wings of War' },
  { code: 'BL20', set: 'BL', number: 20, category: 'Ploy', name: 'Shields Up!' },
  { code: 'BL21', set: 'BL', number: 21, category: 'Ploy', name: 'Scream of Anger' },
  { code: 'BL22', set: 'BL', number: 22, category: 'Ploy', name: 'Healing Potion' },
  { code: 'ES13', set: 'ES', number: 13, category: 'Ploy', name: 'Switch Things Up' },
  { code: 'ES14', set: 'ES', number: 14, category: 'Ploy', name: 'Sidestep' },
  { code: 'ES15', set: 'ES', number: 15, category: 'Ploy', name: 'The Extra Mile' },
  { code: 'ES16', set: 'ES', number: 16, category: 'Ploy', name: 'Settle In' },
  { code: 'ES17', set: 'ES', number: 17, category: 'Ploy', name: 'Healing Potion' },
  { code: 'ES18', set: 'ES', number: 18, category: 'Ploy', name: 'Hidden Paths' },
  { code: 'ES19', set: 'ES', number: 19, category: 'Ploy', name: 'Confusion' },
  { code: 'ES20', set: 'ES', number: 20, category: 'Ploy', name: 'Hold the Line!' },
  { code: 'ES21', set: 'ES', number: 21, category: 'Ploy', name: 'Shoulder Throw' },
  { code: 'ES22', set: 'ES', number: 22, category: 'Ploy', name: 'By the Numbers' },
  { code: 'PL13', set: 'PL', number: 13, category: 'Ploy', name: 'Sidestep' },
  { code: 'PL14', set: 'PL', number: 14, category: 'Ploy', name: 'Prideful Duellist' },
  { code: 'PL15', set: 'PL', number: 15, category: 'Ploy', name: 'Commanding Stride' },
  { code: 'PL16', set: 'PL', number: 16, category: 'Ploy', name: 'Crumbling Mine' },
  { code: 'PL17', set: 'PL', number: 17, category: 'Ploy', name: 'Explosive Charges' },
  { code: 'PL18', set: 'PL', number: 18, category: 'Ploy', name: 'Wary Delver' },
  { code: 'PL19', set: 'PL', number: 19, category: 'Ploy', name: 'Brash Scout' },
  { code: 'PL20', set: 'PL', number: 20, category: 'Ploy', name: 'Sudden Blast' },
  { code: 'PL21', set: 'PL', number: 21, category: 'Ploy', name: 'Tunnelling Terror' },
  { code: 'PL22', set: 'PL', number: 22, category: 'Ploy', name: 'Trapped Cache' },
  { code: 'CC13', set: 'CC', number: 13, category: 'Ploy', name: 'Savage Blow' },
  { code: 'CC14', set: 'CC', number: 14, category: 'Ploy', name: 'The End is Nigh' },
  { code: 'CC15', set: 'CC', number: 15, category: 'Ploy', name: 'Growing Concerns' },
  { code: 'CC16', set: 'CC', number: 16, category: 'Ploy', name: 'Total Collapse' },
  { code: 'CC17', set: 'CC', number: 17, category: 'Ploy', name: 'Violent Blast' },
  { code: 'CC18', set: 'CC', number: 18, category: 'Ploy', name: 'Sunder the Realm' },
  { code: 'CC19', set: 'CC', number: 19, category: 'Ploy', name: 'Raging Tremors' },
  { code: 'CC20', set: 'CC', number: 20, category: 'Ploy', name: 'Counter-charge' },
  { code: 'CC21', set: 'CC', number: 21, category: 'Ploy', name: 'Do or Die' },
  { code: 'CC22', set: 'CC', number: 22, category: 'Ploy', name: 'Improvised Attack' },
  { code: 'RF13', set: 'RF', number: 13, category: 'Ploy', name: 'Braced' },
  { code: 'RF14', set: 'RF', number: 14, category: 'Ploy', name: 'Catch Weapon' },
  { code: 'RF15', set: 'RF', number: 15, category: 'Ploy', name: 'Diving In' },
  { code: 'RF16', set: 'RF', number: 16, category: 'Ploy', name: 'Get It Done' },
  { code: 'RF17', set: 'RF', number: 17, category: 'Ploy', name: 'Lost Legacy' },
  { code: 'RF18', set: 'RF', number: 18, category: 'Ploy', name: 'Outburst' },
  { code: 'RF19', set: 'RF', number: 19, category: 'Ploy', name: 'Over to You' },
  { code: 'RF20', set: 'RF', number: 20, category: 'Ploy', name: 'Push Through' },
  { code: 'RF21', set: 'RF', number: 21, category: 'Ploy', name: 'Quick Shift' },
  { code: 'RF22', set: 'RF', number: 22, category: 'Ploy', name: 'Reckless Attitudes' },
  { code: 'WR13', set: 'WR', number: 13, category: 'Ploy', name: 'Confusion' },
  { code: 'WR14', set: 'WR', number: 14, category: 'Ploy', name: 'Damned if you Do' },
  { code: 'WR15', set: 'WR', number: 15, category: 'Ploy', name: 'Deadly Traps' },
  { code: 'WR16', set: 'WR', number: 16, category: 'Ploy', name: 'Fault Lines' },
  { code: 'WR17', set: 'WR', number: 17, category: 'Ploy', name: 'Fireproof' },
  { code: 'WR18', set: 'WR', number: 18, category: 'Ploy', name: 'Flee!' },
  { code: 'WR19', set: 'WR', number: 19, category: 'Ploy', name: 'Ominous Rumbling' },
  { code: 'WR20', set: 'WR', number: 20, category: 'Ploy', name: 'Sidle Up' },
  { code: 'WR21', set: 'WR', number: 21, category: 'Ploy', name: 'Vicious Intent' },
  { code: 'WR22', set: 'WR', number: 22, category: 'Ploy', name: 'Volcanic Eruption' },
  { code: 'EK13', set: 'EK', number: 13, category: 'Ploy', name: 'Death Throes' },
  { code: 'EK14', set: 'EK', number: 14, category: 'Ploy', name: 'Fake Out!' },
  { code: 'EK15', set: 'EK', number: 15, category: 'Ploy', name: 'Final Stand' },
  { code: 'EK16', set: 'EK', number: 16, category: 'Ploy', name: 'Opportunity Strikes' },
  { code: 'EK17', set: 'EK', number: 17, category: 'Ploy', name: 'Power from Death' },
  { code: 'EK18', set: 'EK', number: 18, category: 'Ploy', name: 'Running Riot' },
  { code: 'EK19', set: 'EK', number: 19, category: 'Ploy', name: 'Sidestep' },
  { code: 'EK20', set: 'EK', number: 20, category: 'Ploy', name: 'Spiteful Traps' },
  { code: 'EK21', set: 'EK', number: 21, category: 'Ploy', name: 'Synchronised Effort' },
  { code: 'EK22', set: 'EK', number: 22, category: 'Ploy', name: 'The Uprising!' },
  { code: 'RS13', set: 'RS', number: 13, category: 'Ploy', name: 'Ambush' },
  { code: 'RS14', set: 'RS', number: 14, category: 'Ploy', name: 'Angered Focus' },
  { code: 'RS15', set: 'RS', number: 15, category: 'Ploy', name: 'A Step Ahead' },
  { code: 'RS16', set: 'RS', number: 16, category: 'Ploy', name: 'Fortune Faded' },
  { code: 'RS17', set: 'RS', number: 17, category: 'Ploy', name: 'Hidden Knowledge' },
  { code: 'RS18', set: 'RS', number: 18, category: 'Ploy', name: 'Intoxicated with Rage' },
  { code: 'RS19', set: 'RS', number: 19, category: 'Ploy', name: 'Manipulated Fate' },
  { code: 'RS20', set: 'RS', number: 20, category: 'Ploy', name: 'Misstep' },
  { code: 'RS21', set: 'RS', number: 21, category: 'Ploy', name: 'Raider\'s Rapture' },
  { code: 'RS22', set: 'RS', number: 22, category: 'Ploy', name: 'Raider\'s Premonition' },
  { code: 'RG13', set: 'RG', number: 13, category: 'Ploy', name: 'Adrenaline Rush' },
  { code: 'RG14', set: 'RG', number: 14, category: 'Ploy', name: 'Honed Reflexes' },
  { code: 'RG15', set: 'RG', number: 15, category: 'Ploy', name: 'Knife to the Heart' },
  { code: 'RG16', set: 'RG', number: 16, category: 'Ploy', name: 'Murderlust' },
  { code: 'RG17', set: 'RG', number: 17, category: 'Ploy', name: 'Senseless Haste' },
  { code: 'RG18', set: 'RG', number: 18, category: 'Ploy', name: 'Slayer\'s Aid' },
  { code: 'RG19', set: 'RG', number: 19, category: 'Ploy', name: 'Slayer\'s Arena' },
  { code: 'RG20', set: 'RG', number: 20, category: 'Ploy', name: 'Venting Strike' },
  { code: 'RG21', set: 'RG', number: 21, category: 'Ploy', name: 'What Pain?' },
  { code: 'RG22', set: 'RG', number: 22, category: 'Ploy', name: 'Wrong-footed Stance' },
  { code: 'HG13', set: 'HG', number: 13, category: 'Ploy', name: 'Audacious Denial' },
  { code: 'HG14', set: 'HG', number: 14, category: 'Ploy', name: 'Deny Invaders' },
  { code: 'HG15', set: 'HG', number: 15, category: 'Ploy', name: 'Hidden Snares' },
  { code: 'HG16', set: 'HG', number: 16, category: 'Ploy', name: 'Keep Them at Bay' },
  { code: 'HG17', set: 'HG', number: 17, category: 'Ploy', name: 'Mind Your Step' },
  { code: 'HG18', set: 'HG', number: 18, category: 'Ploy', name: 'Mystical Misdirection' },
  { code: 'HG19', set: 'HG', number: 19, category: 'Ploy', name: 'Paths Unknown' },
  { code: 'HG20', set: 'HG', number: 20, category: 'Ploy', name: 'Poor Footing' },
  { code: 'HG21', set: 'HG', number: 21, category: 'Ploy', name: 'Secrets of the Realm' },
  { code: 'HG22', set: 'HG', number: 22, category: 'Ploy', name: 'Sidestep' },
  { code: 'DY13', set: 'DY', number: 13, category: 'Ploy', name: 'Another Swing' },
  { code: 'DY14', set: 'DY', number: 14, category: 'Ploy', name: 'Army of Two' },
  { code: 'DY15', set: 'DY', number: 15, category: 'Ploy', name: 'Brother-in-Arms' },
  { code: 'DY16', set: 'DY', number: 16, category: 'Ploy', name: 'Defiant Duo' },
  { code: 'DY17', set: 'DY', number: 17, category: 'Ploy', name: 'Out of Nowhere' },
  { code: 'DY18', set: 'DY', number: 18, category: 'Ploy', name: 'Selfless Parry' },
  { code: 'DY19', set: 'DY', number: 19, category: 'Ploy', name: 'Sidestep' },
  { code: 'DY20', set: 'DY', number: 20, category: 'Ploy', name: 'Take One for the Team' },
  { code: 'DY21', set: 'DY', number: 21, category: 'Ploy', name: 'Timed Strike' },
  { code: 'DY22', set: 'DY', number: 22, category: 'Ploy', name: 'Unified Front' },
  { code: 'NP13', set: 'NP', number: 13, category: 'Ploy', name: 'Pilfer' },
  { code: 'NP14', set: 'NP', number: 14, category: 'Ploy', name: 'Move at the Opening' },
  { code: 'NP15', set: 'NP', number: 15, category: 'Ploy', name: 'Organised Efforts' },
  { code: 'NP16', set: 'NP', number: 16, category: 'Ploy', name: 'Defiance' },
  { code: 'NP17', set: 'NP', number: 17, category: 'Ploy', name: 'Into the Deepwoods' },
  { code: 'NP18', set: 'NP', number: 18, category: 'Ploy', name: 'Unearthed Treasure' },
  { code: 'NP19', set: 'NP', number: 19, category: 'Ploy', name: 'Territorial Welcome' },
  { code: 'NP20', set: 'NP', number: 20, category: 'Ploy', name: 'Hold the Line!' },
  { code: 'NP21', set: 'NP', number: 21, category: 'Ploy', name: 'Dig In' },
  { code: 'NP22', set: 'NP', number: 22, category: 'Ploy', name: 'The High Ground' },
  // ---- Upgrades ----
  { code: 'BL23', set: 'BL', number: 23, category: 'Upgrade', name: 'Brawler' },
  { code: 'BL24', set: 'BL', number: 24, category: 'Upgrade', name: 'Hidden Aid' },
  { code: 'BL25', set: 'BL', number: 25, category: 'Upgrade', name: 'Accurate' },
  { code: 'BL26', set: 'BL', number: 26, category: 'Upgrade', name: 'Great Strength' },
  { code: 'BL27', set: 'BL', number: 27, category: 'Upgrade', name: 'Deadly Aim' },
  { code: 'BL28', set: 'BL', number: 28, category: 'Upgrade', name: 'Sharpened Points' },
  { code: 'BL29', set: 'BL', number: 29, category: 'Upgrade', name: 'Duellist' },
  { code: 'BL30', set: 'BL', number: 30, category: 'Upgrade', name: 'Tough' },
  { code: 'BL31', set: 'BL', number: 31, category: 'Upgrade', name: 'Great Fortitude' },
  { code: 'BL32', set: 'BL', number: 32, category: 'Upgrade', name: 'Keen Eye' },
  { code: 'ES23', set: 'ES', number: 23, category: 'Upgrade', name: 'Stubborn to the End' },
  { code: 'ES24', set: 'ES', number: 24, category: 'Upgrade', name: 'Inviolate' },
  { code: 'ES25', set: 'ES', number: 25, category: 'Upgrade', name: 'Great Speed' },
  { code: 'ES26', set: 'ES', number: 26, category: 'Upgrade', name: 'Sharp Reflexes' },
  { code: 'ES27', set: 'ES', number: 27, category: 'Upgrade', name: 'Brute Momentum' },
  { code: 'ES28', set: 'ES', number: 28, category: 'Upgrade', name: 'Agile' },
  { code: 'ES29', set: 'ES', number: 29, category: 'Upgrade', name: 'Duellist' },
  { code: 'ES30', set: 'ES', number: 30, category: 'Upgrade', name: 'Great Fortitude' },
  { code: 'ES31', set: 'ES', number: 31, category: 'Upgrade', name: 'Keen Eye' },
  { code: 'ES32', set: 'ES', number: 32, category: 'Upgrade', name: 'Great Strength' },
  { code: 'PL23', set: 'PL', number: 23, category: 'Upgrade', name: 'Great Speed' },
  { code: 'PL24', set: 'PL', number: 24, category: 'Upgrade', name: 'Swift Step' },
  { code: 'PL25', set: 'PL', number: 25, category: 'Upgrade', name: 'Burrowing Strike' },
  { code: 'PL26', set: 'PL', number: 26, category: 'Upgrade', name: 'Tough Enough' },
  { code: 'PL27', set: 'PL', number: 27, category: 'Upgrade', name: 'Canny Sapper' },
  { code: 'PL28', set: 'PL', number: 28, category: 'Upgrade', name: 'Impossibly Quick' },
  { code: 'PL29', set: 'PL', number: 29, category: 'Upgrade', name: 'Linebreaker' },
  { code: 'PL30', set: 'PL', number: 30, category: 'Upgrade', name: 'Excavating Blast' },
  { code: 'PL31', set: 'PL', number: 31, category: 'Upgrade', name: 'Gloryseeker' },
  { code: 'PL32', set: 'PL', number: 32, category: 'Upgrade', name: 'Frenzy of Greed' },
  { code: 'CC23', set: 'CC', number: 23, category: 'Upgrade', name: 'Bringer of Doom' },
  { code: 'CC24', set: 'CC', number: 24, category: 'Upgrade', name: 'Visions of Ruin' },
  { code: 'CC25', set: 'CC', number: 25, category: 'Upgrade', name: 'Extinction\'s Edge' },
  { code: 'CC26', set: 'CC', number: 26, category: 'Upgrade', name: 'Driven by Pain' },
  { code: 'CC27', set: 'CC', number: 27, category: 'Upgrade', name: 'Inescapable Grasp' },
  { code: 'CC28', set: 'CC', number: 28, category: 'Upgrade', name: 'Utter Conviction' },
  { code: 'CC29', set: 'CC', number: 29, category: 'Upgrade', name: 'Burnt Out' },
  { code: 'CC30', set: 'CC', number: 30, category: 'Upgrade', name: 'Great Fortitude' },
  { code: 'CC31', set: 'CC', number: 31, category: 'Upgrade', name: 'Hurled Weapon' },
  { code: 'CC32', set: 'CC', number: 32, category: 'Upgrade', name: 'Desperate Rage' },
  { code: 'RF23', set: 'RF', number: 23, category: 'Upgrade', name: 'Bellowing Tyrant' },
  { code: 'RF24', set: 'RF', number: 24, category: 'Upgrade', name: 'Bladecatcher' },
  { code: 'RF25', set: 'RF', number: 25, category: 'Upgrade', name: 'Blades of Wrath' },
  { code: 'RF26', set: 'RF', number: 26, category: 'Upgrade', name: 'Furious Might' },
  { code: 'RF27', set: 'RF', number: 27, category: 'Upgrade', name: 'Fury of Aqshy' },
  { code: 'RF28', set: 'RF', number: 28, category: 'Upgrade', name: 'Headcase' },
  { code: 'RF29', set: 'RF', number: 29, category: 'Upgrade', name: 'Headlong Charge' },
  { code: 'RF30', set: 'RF', number: 30, category: 'Upgrade', name: 'Keen Eye' },
  { code: 'RF31', set: 'RF', number: 31, category: 'Upgrade', name: 'Still Swinging' },
  { code: 'RF32', set: 'RF', number: 32, category: 'Upgrade', name: 'Utter Ignorance' },
  { code: 'WR23', set: 'WR', number: 23, category: 'Upgrade', name: 'Barge' },
  { code: 'WR24', set: 'WR', number: 24, category: 'Upgrade', name: 'Desperate Defence' },
  { code: 'WR25', set: 'WR', number: 25, category: 'Upgrade', name: 'Fiery Temper' },
  { code: 'WR26', set: 'WR', number: 26, category: 'Upgrade', name: 'Great Speed' },
  { code: 'WR27', set: 'WR', number: 27, category: 'Upgrade', name: 'Henchman' },
  { code: 'WR28', set: 'WR', number: 28, category: 'Upgrade', name: 'Misfortune' },
  { code: 'WR29', set: 'WR', number: 29, category: 'Upgrade', name: 'Rock-splitting Tread' },
  { code: 'WR30', set: 'WR', number: 30, category: 'Upgrade', name: 'Sundering Weapon' },
  { code: 'WR31', set: 'WR', number: 31, category: 'Upgrade', name: 'Unstoppable' },
  { code: 'WR32', set: 'WR', number: 32, category: 'Upgrade', name: 'Wary Tread' },
  { code: 'EK23', set: 'EK', number: 23, category: 'Upgrade', name: 'Dark Horse' },
  { code: 'EK24', set: 'EK', number: 24, category: 'Upgrade', name: 'Deadly Aim' },
  { code: 'EK25', set: 'EK', number: 25, category: 'Upgrade', name: 'Fuelled by Pain' },
  { code: 'EK26', set: 'EK', number: 26, category: 'Upgrade', name: 'Great Fortitude' },
  { code: 'EK27', set: 'EK', number: 27, category: 'Upgrade', name: 'Impervious' },
  { code: 'EK28', set: 'EK', number: 28, category: 'Upgrade', name: 'Lash Out' },
  { code: 'EK29', set: 'EK', number: 29, category: 'Upgrade', name: 'Mobbed!' },
  { code: 'EK30', set: 'EK', number: 30, category: 'Upgrade', name: 'Parting Shot' },
  { code: 'EK31', set: 'EK', number: 31, category: 'Upgrade', name: 'Pesky Nuisance' },
  { code: 'EK32', set: 'EK', number: 32, category: 'Upgrade', name: 'Sharpened Points' },
  { code: 'RS23', set: 'RS', number: 23, category: 'Upgrade', name: 'Armour Piercer' },
  { code: 'RS24', set: 'RS', number: 24, category: 'Upgrade', name: 'Brightstone Vigour' },
  { code: 'RS25', set: 'RS', number: 25, category: 'Upgrade', name: 'Call to Power' },
  { code: 'RS26', set: 'RS', number: 26, category: 'Upgrade', name: 'Emberstone Edge' },
  { code: 'RS27', set: 'RS', number: 27, category: 'Upgrade', name: 'Forgotten Fortune' },
  { code: 'RS28', set: 'RS', number: 28, category: 'Upgrade', name: 'Great Fortitude' },
  { code: 'RS29', set: 'RS', number: 29, category: 'Upgrade', name: 'Great Speed' },
  { code: 'RS30', set: 'RS', number: 30, category: 'Upgrade', name: 'Great Strength' },
  { code: 'RS31', set: 'RS', number: 31, category: 'Upgrade', name: 'Keen Eye' },
  { code: 'RS32', set: 'RS', number: 32, category: 'Upgrade', name: 'Reforged Aid' },
  { code: 'RG23', set: 'RG', number: 23, category: 'Upgrade', name: 'Agile' },
  { code: 'RG24', set: 'RG', number: 24, category: 'Upgrade', name: 'Aggressive Ambusher' },
  { code: 'RG25', set: 'RG', number: 25, category: 'Upgrade', name: 'Angered Swing' },
  { code: 'RG26', set: 'RG', number: 26, category: 'Upgrade', name: 'Assured Bloodshed' },
  { code: 'RG27', set: 'RG', number: 27, category: 'Upgrade', name: 'Gifted Vitality' },
  { code: 'RG28', set: 'RG', number: 28, category: 'Upgrade', name: 'Haymaker' },
  { code: 'RG29', set: 'RG', number: 29, category: 'Upgrade', name: 'Keen Eye' },
  { code: 'RG30', set: 'RG', number: 30, category: 'Upgrade', name: 'Murderous Instincts' },
  { code: 'RG31', set: 'RG', number: 31, category: 'Upgrade', name: 'Stubborn to the Bone' },
  { code: 'RG32', set: 'RG', number: 32, category: 'Upgrade', name: 'United in Anger' },
  { code: 'HG23', set: 'HG', number: 23, category: 'Upgrade', name: 'Balance of Ghyran' },
  { code: 'HG24', set: 'HG', number: 24, category: 'Upgrade', name: 'Blocked!' },
  { code: 'HG25', set: 'HG', number: 25, category: 'Upgrade', name: 'Bounty of Ghyran' },
  { code: 'HG26', set: 'HG', number: 26, category: 'Upgrade', name: 'Crippling Blow' },
  { code: 'HG27', set: 'HG', number: 27, category: 'Upgrade', name: 'Goading Defender' },
  { code: 'HG28', set: 'HG', number: 28, category: 'Upgrade', name: 'Great Speed' },
  { code: 'HG29', set: 'HG', number: 29, category: 'Upgrade', name: 'Hidden Aid' },
  { code: 'HG30', set: 'HG', number: 30, category: 'Upgrade', name: 'Hidden Traps' },
  { code: 'HG31', set: 'HG', number: 31, category: 'Upgrade', name: 'Killing Blow' },
  { code: 'HG32', set: 'HG', number: 32, category: 'Upgrade', name: 'True Grit' },
  { code: 'DY23', set: 'DY', number: 23, category: 'Upgrade', name: 'Battering Ram' },
  { code: 'DY24', set: 'DY', number: 24, category: 'Upgrade', name: 'Coordinated Deathblow' },
  { code: 'DY25', set: 'DY', number: 25, category: 'Upgrade', name: 'Duellist' },
  { code: 'DY26', set: 'DY', number: 26, category: 'Upgrade', name: 'Entangling Strike' },
  { code: 'DY27', set: 'DY', number: 27, category: 'Upgrade', name: 'Great Fortitude' },
  { code: 'DY28', set: 'DY', number: 28, category: 'Upgrade', name: 'Keen Eye' },
  { code: 'DY29', set: 'DY', number: 29, category: 'Upgrade', name: 'Rush to Aid' },
  { code: 'DY30', set: 'DY', number: 30, category: 'Upgrade', name: 'Shared Incentive' },
  { code: 'DY31', set: 'DY', number: 31, category: 'Upgrade', name: 'Spurred Momentum' },
  { code: 'DY32', set: 'DY', number: 32, category: 'Upgrade', name: 'Titan of Combat' },
  { code: 'NP23', set: 'NP', number: 23, category: 'Upgrade', name: 'Wily Prospector' },
  { code: 'NP24', set: 'NP', number: 24, category: 'Upgrade', name: 'Cautious Attitude' },
  { code: 'NP25', set: 'NP', number: 25, category: 'Upgrade', name: 'Mirror Shield' },
  { code: 'NP26', set: 'NP', number: 26, category: 'Upgrade', name: 'Driven by Pain' },
  { code: 'NP27', set: 'NP', number: 27, category: 'Upgrade', name: 'Inviolate' },
  { code: 'NP28', set: 'NP', number: 28, category: 'Upgrade', name: 'Opportunist' },
  { code: 'NP29', set: 'NP', number: 29, category: 'Upgrade', name: 'Overreach' },
  { code: 'NP30', set: 'NP', number: 30, category: 'Upgrade', name: 'Spiteful Defender' },
  { code: 'NP31', set: 'NP', number: 31, category: 'Upgrade', name: 'I Like Those Odds' },
  { code: 'NP32', set: 'NP', number: 32, category: 'Upgrade', name: 'Starmaw' },
];

export const CARD_BY_CODE = CARDS.reduce(function (m, c) {
  m[c.code] = c;
  return m;
}, {});

export function cardName(code) {
  const c = CARD_BY_CODE[code];
  return c ? c.name : code;
}

export function cardsBySet(prefix) {
  return CARDS.filter(function (c) { return c.set === prefix; });
}

export function cardsByCategory(category) {
  return CARDS.filter(function (c) { return c.category === category; });
}
